id: P1FF74AAC
initial_creation_type: input
source_metadata:
  title: Thönmi Sambhoṭa Series
  language: en
  description: 'Texts by and about Thönmi Sambhoṭa, who is credited with inventing
    the Tibetan writing system and composing the country''s first grammatical treatises:'
  volume:
    b860f8c794ed495d87caf28768386060:
      title: 'A Blossoming of the Intellect: In Praise of the Great Pioneer Thönmi
        Sambhoṭa'
      parent: Praise
created_at: '2022-03-01T01:48:50.473946'
last_modified_at: '2022-03-01T01:48:50.473951'
